name: learnmate_app
description: LearnMate - AI-powered learning assistant app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Authentication
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.1.6
  
  # Audio & Animations
  audioplayers: ^5.2.1
  lottie: ^2.7.0
  
  # HTTP & Utils
  provider: ^6.1.1  
  http: ^1.1.0 
  google_fonts: ^6.1.0
  
  # UI Enhancements
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    
